name: Build

on:
  push
  
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Restore
        run: dotnet restore  
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish 
        run: dotnet publish EFCore.Postgres -c Release --no-build -o /tmp/output
        
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/mortenrickirasmussen/index.json" -UserName "mortenrickirasmussen" -Password "$REGISTRY_PASSWORD"
        env: 
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Push to registry
        run: nuget push /tmp/output/EFCore.Postgres.nupkg -Source "GPR"
