name: Build

on:
  push
  
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Restore
        run: dotnet restore  
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish 
        run: dotnet publish EFCore.Postgres -c Release --no-build -o D:\tmp\output\
        
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/mortenrickirasmussen/index.json -Username mortenrickirasmussen -Password ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Push to registry
        run: nuget push D:\tmp\output\*.nupkg -Source "GPR"
